### ISSUE TITLE
Try on rustc

### ISSUE THREAD

**Issue by bjorn3** [est31/warnalyzer#2]
Might be fun to find out how much of rustc is actually unused.

**Comment by est31** [comment]
Thanks for your interest in warnalyzer!

Rustc is definitely one of the targets. You need to watch out though because projects like clippy use rustc as well. Also, there are a few bugs in save-analysis generation in rustc which create tons of false positives (see readme). So be ready for the main job being filtering out of false positives :). Someone familiar with rustc using warnalyzer is a *very* great idea as this increases the chances of those bugs fixed dramatically :p.

You could probably add the save-analysis flag somewhere in rustbuild's rustc wrapper and build stage0 compiler artifacts with it. Then point warnalyzer at the rustc binary crate.

If you need any help, I'm right there.

**Comment by bjorn3** [comment]
> So be ready for the main job being filtering out of false positives :)

:)

> If you need any help, I'm right there.

Thanks!

**Comment by bjorn3** [comment]
```bash
rust $ git diff
diff --git a/src/bootstrap/bin/rustc.rs b/src/bootstrap/bin/rustc.rs
index 9c01de8aa8..bea1f21272 100644
--- a/src/bootstrap/bin/rustc.rs
+++ b/src/bootstrap/bin/rustc.rs
@@ -45,6 +45,9 @@ fn main() {
         }
     }
 
+
+    args.push("-Zsave-analysis".into());
+
     // Detect whether or not we're a build script depending on whether --target
     // is passed (a bit janky...)
     let target = args.windows(2)
rust $ ./x.py check
rust $ cd ../warnalyzer
warnalyzer $ cargo run ../rust/build/x86_64-*/stage0-rustc/x86_64-*/release/deps/save-analysis/rustc_binary-*.json | wc -l
2612
```

**Comment by est31** [comment]
https://github.com/rust-lang/rust/pull/77739 is merged, closing.
