### ISSUE TITLE
Trait implementation methods not considered as used

### ISSUE THREAD

**Issue by bjorn3** [est31/warnalyzer#3]
```rust
trait Abc {
    fn a();
    fn b();
}

struct Bcd;

impl Abc for Bcd {
    fn a() {}
    fn b() {} // considered unused even though it is required
}

fn main() {
    Bcd::a();
}
```

**Comment by est31** [comment]
If the trait's function is being used anywhere even if it's through the impl of another struct, the warning disappears. This snippet is warning-free:

```Rust
trait Abc {
    fn a();
    fn b();
}

struct Bcd;

impl Abc for Bcd {
    fn a() {}
    fn b() {}
}

struct Def;

impl Abc for Def {
    fn a() {}
    fn b() {}
}

fn main() {
    Bcd::a();
}
```

This is done by [this](https://github.com/est31/warnalyzer/blob/58183ed2e45e7c23e5b136ee3c17861b32c66b37/src/db.rs#L188) line in the code. The reasoning is that if `Abc::b()` isn't used at all, then `<Bcd as Abc>::b()` isn't either. That's at least the basic idea. In general warnalyzer doesn't do recursion (doesn't warn in general if some code is only used by unused code) but this instance is some kind of manual mini-recursion. I didn't feel like it's worth implementing recursion now due to the high false positive rate.

Please tell me whether my explanation was helpful and whether this choice is okay in your opinion.

**Comment by bjorn3** [comment]
I understand. It may be useful to ignore it for trait implementations, but keep it for trait definition, so that you only get one warning that the method is unused.
